/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'plywood' : IDL.Null,
  'kitchen' : IDL.Null,
  'electricals' : IDL.Null,
  'hardware' : IDL.Null,
  'wardrobe' : IDL.Null,
  'paints' : IDL.Null,
  'laminates' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Product = IDL.Record({
  'specifications' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'image' : IDL.Text,
});
export const BusinessSettings = IDL.Record({
  'siteVisitTemplate' : IDL.Text,
  'businessHours' : IDL.Text,
  'secondaryPhone' : IDL.Text,
  'estimateMessageTemplate' : IDL.Text,
  'productInquiryTemplate' : IDL.Text,
  'email' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'contractorInquiryTemplate' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'primaryPhone' : IDL.Text,
  'quoteBuilderTemplate' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, Category, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'filterProductsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBusinessSettings' : IDL.Func([], [IDL.Opt(BusinessSettings)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateBusinessSettings' : IDL.Func([BusinessSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'plywood' : IDL.Null,
    'kitchen' : IDL.Null,
    'electricals' : IDL.Null,
    'hardware' : IDL.Null,
    'wardrobe' : IDL.Null,
    'paints' : IDL.Null,
    'laminates' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Product = IDL.Record({
    'specifications' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'image' : IDL.Text,
  });
  const BusinessSettings = IDL.Record({
    'siteVisitTemplate' : IDL.Text,
    'businessHours' : IDL.Text,
    'secondaryPhone' : IDL.Text,
    'estimateMessageTemplate' : IDL.Text,
    'productInquiryTemplate' : IDL.Text,
    'email' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'contractorInquiryTemplate' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'primaryPhone' : IDL.Text,
    'quoteBuilderTemplate' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, Category, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'filterProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBusinessSettings' : IDL.Func(
        [],
        [IDL.Opt(BusinessSettings)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateBusinessSettings' : IDL.Func([BusinessSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };