/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessSettings {
  'siteVisitTemplate' : string,
  'businessHours' : string,
  'secondaryPhone' : string,
  'estimateMessageTemplate' : string,
  'productInquiryTemplate' : string,
  'email' : string,
  'whatsappNumber' : string,
  'contractorInquiryTemplate' : string,
  'address' : string,
  'companyName' : string,
  'primaryPhone' : string,
  'quoteBuilderTemplate' : string,
}
export type Category = { 'plywood' : null } |
  { 'kitchen' : null } |
  { 'electricals' : null } |
  { 'hardware' : null } |
  { 'wardrobe' : null } |
  { 'paints' : null } |
  { 'laminates' : null };
export interface Product {
  'specifications' : string,
  'name' : string,
  'description' : string,
  'category' : Category,
  'image' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, Category, string, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'filterProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBusinessSettings' : ActorMethod<[], [] | [BusinessSettings]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateBusinessSettings' : ActorMethod<[BusinessSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];